sudo: false
language: scala
jdk:
- openjdk8
- openjdk11
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
script:
- git clone https://github.com/gitbucket/gitbucket.git
- cd gitbucket
- sbt publishLocal
- cd ../
- sbt test
