CREATE TABLE GIST (
	USER_NAME VARCHAR(100) NOT NULL,
	REPOSITORY_NAME VARCHAR(100) NOT NULL,
	PRIVATE BOOLEAN NOT NULL,
  TITLE VARCHAR(100) NOT NULL,
	DESCRIPTION TEXT,
	REGISTERED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE GIST_COMMENT(
	USER_NAME VARCHAR(100) NOT NULL,
	REPOSITORY_NAME VARCHAR(100) NOT NULL,
	COMMENT_ID INT AUTO_INCREMENT,
	COMMENTED_USER_NAME VARCHAR(100) NOT NULL,
	CONTENT TEXT NOT NULL,
	REGISTERED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL
);

ALTER TABLE GIST ADD CONSTRAINT IDX_GIST_PK PRIMARY KEY (USER_NAME, REPOSITORY_NAME);
ALTER TABLE GIST ADD CONSTRAINT IDX_GIST_FK0 FOREIGN KEY (USER_NAME) REFERENCES ACCOUNT (USER_NAME);

ALTER TABLE GIST_COMMENT ADD CONSTRAINT IDX_GIST_COMMENT_PK PRIMARY KEY (COMMENT_ID);
ALTER TABLE GIST_COMMENT ADD CONSTRAINT IDX_GIST_COMMENT_1 UNIQUE (USER_NAME, REPOSITORY_NAME, COMMENT_ID);
ALTER TABLE GIST_COMMENT ADD CONSTRAINT IDX_GIST_COMMENT_FK0 FOREIGN KEY (USER_NAME, REPOSITORY_NAME) REFERENCES GIST (USER_NAME, REPOSITORY_NAME);
ALTER TABLE GIST_COMMENT ADD CONSTRAINT IDX_GIST_COMMENT_FK1 FOREIGN KEY (COMMENTED_USER_NAME) REFERENCES ACCOUNT (USER_NAME);
