ALTER TABLE GIST ADD COLUMN ORIGIN_USER_NAME VARCHAR(100);
ALTER TABLE GIST ADD COLUMN ORIGIN_REPOSITORY_NAME VARCHAR(100);
ALTER TABLE GIST ADD COLUMN PARENT_USER_NAME VARCHAR(100);
ALTER TABLE GIST ADD COLUMN PARENT_REPOSITORY_NAME VARCHAR(100);
